### ISSUE TITLE
Problem use()ing plotnine in jupyter

### ISSUE THREAD

**Issue by amogorkon** [amogorkon/justuse#23]
```
import use
p9 = use("plotnine", version="0.7.1")
```
results in 
```
/home/thorsten/anaconda3/lib/python3.8/site-packages/palettable/colorbrewer/colorbrewer.py:7: 
UserWarning: Module use was already imported from None, but /media/sf_Dropbox/code/justuse/src is being added to sys.path
```

**Comment by amogorkon** [comment]
from SO:
"
It means there is an entry sys.modules['dap'] that does not have a path. It's a warning, btw, not an exception, so it may be okay. What does print sys.modules['dap']"
"
That means it has no filename; it automatically is marked as (built-in). Interesting, I wonder what poked that in there. "

**Comment by amogorkon** [comment]
Looks like the issue is that a Use() object has no `__path__`?

**Comment by greyblue9** [comment]
That must be where it gets the idea it was imported `from None` -- this library thinks Use is a module I expect?

**Comment by amogorkon** [comment]
I've added `__path__` to Use, now with `use.__path__` I get '/media/sf_Dropbox/code/justuse/src/use', but the Warning persists:

`
/home/thorsten/anaconda3/lib/python3.8/site-packages/palettable/colorbrewer/colorbrewer.py:7: UserWarning: Module use was already imported from None, but /media/sf_Dropbox/code/justuse/src is being added to sys.path
`

**Comment by amogorkon** [comment]
Ehhh.. I fixed it the warning?
If I %cd /media/sf_Dropbox/code/justuse/src/use instead of %cd /media/sf_Dropbox/code/justuse/src/, the warning disappears, what's going on there?
