### ISSUE TITLE
make use install()able - globally add to builtins

### ISSUE THREAD

**Issue by amogorkon** [amogorkon/justuse#29]
from the icecream docs:

To make ic() available in every file without needing to be imported in every file, you can install() it.

install() adds ic() to the builtins module, which is shared amongst all files imported by the interpreter. Similarly, ic() can later be uninstall()ed, too.

use should have that too :)

**Comment by greyblue9** [comment]
To have use() available globally?
How does the user indicate this? I assume we don't want to do it by default?
