### ISSUE TITLE
reload only works properly in jupyter - make it work everywhere!

### ISSUE THREAD

**Issue by amogorkon** [amogorkon/justuse#3]
the hybrid async/non-async code around reload doesn't work in a purely non-async environment, however jupyter is an async environment, which kind of works around that limitation.

**Comment by greyblue9** [comment]
Is it because jupyter has already started an event loop, but vanilla python does not have an already-running event loop?

**Comment by amogorkon** [comment]
Wow, that was a difficult birth.. but now it works. I'm closing it, anything else should be reported as new bugs. We also need to refactor the whole thing (after writing tests, I guess), but that shouldn't concern this issue.
