### ISSUE TITLE
Version upgrade warning like pip?

### ISSUE THREAD

**Issue by amogorkon** [amogorkon/justuse#47]
```
WARNING: You are using pip version 21.1.2; however, version 21.1.3 is available.
You should consider upgrading via the 'C:\Users\micro\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.
```
We similarly could check for the newest version in `Use.__init__` and warn the user whenever a new version is available, although we'll need a new class of Warning so users can filter it and/or we could add a config setting to disable the warning.

**Comment by greyblue9** [comment]
@amogorkon The version of justuse?

**Comment by amogorkon** [comment]
yeah
