### ISSUE TITLE
it should be possible to optionally auto-install packages

### ISSUE THREAD

**Issue by amogorkon** [amogorkon/justuse#7]
use() should take an "auto_install" argument in conjunction with a specified version. Version-pinning is much more picky than the package-management approach of "greater/smaller than" version-specifiers. While pinning solves any incompatibility issues that come with API changes (and even upstream corruption), it might involve a lot more manual work with installing and managing virtual envs.
For the usecases that use() is designed to solve - fiddly, non-production code that is imported from *anywhere but* a locally, well groomed package, trying to maintain best-practices with a virtual env and installing everything manually is quite a hassle.
There is also no way for an external package manager to maintain those packages automatically because there usually is no additional metadata to go on other than the code-module itself.
Also, if you use(some local file or external URL), there is nothing to go on for classical package managers, so the installation must either be done by the user before running the code, making educated guess about what to install - if the used() code also uses() their external dependencies however, this can be done automatically, efficiently and safely.

**Comment by greyblue9** [comment]
Where would the `auto-install`'ed modules be installed to? Currently running python interpreter? Some virtual env? Home directory python lib directory?

**Comment by amogorkon** [comment]
Very good question. Before we can answer that, we need to clarify what "install" actually means.
What is the actual step pip takes between downloading the zip and "import package"?

**Comment by amogorkon** [comment]
I'm thinking of a Path.home() / justuse as base, with a config.ini, a registry.json and maybe a usage.log (like you suggested) in there. In the config, one could set things like where to install packages to (which in my case will definitely not be on the SSD where my windows-home is due to space limitations, so that's a given)  as well as future P2P settings etc.
The registry.json will map directly to a dict in the code, initialized with all the currently pip-installed site packages, keeping track of additional, version&hash-pinned packages installed by justuse.
As a default, there could be a /packages folder where auto-installed packages could live, away from any site-packages etc. that might confuse pip and classical imports since any number of versions could happily co-exist in there.
